### ISSUE TITLE
404 in link @ https://ethereum.org/ether

### ISSUE THREAD

**Issue by redaktor** [ethereum/frontier-release#111]
See https://ethereum.org/ether --> paragraph _"WHAT IS ETHER?"_

```html
<strong>
  If you just want to test the technology, you probably don't need real ether. 
    <a href="../geth/">Just deploy a private test net</a> 
  and you will be able get free test ether by mining
</strong>
```
Not sure what ```<a href="../geth/">``` should be but it returns 404.
Proposal: Link to https://github.com/ethereum/go-ethereum/wiki/geth ...

**Comment by dawsonbotsford** [comment]
Still broken for me

**Comment by redaktor** [comment]
:+1:  This works now. Well done. cheers + closing now.
