### ISSUE TITLE
No reset during Frontier to Homestead

### ISSUE THREAD

**Issue by linagee** [ethereum/frontier-release#38]
https://github.com/ethereum/frontier-release/blob/master/bin/install.sh#L496

states: "we will preserve all non-contract (i.e. code-less) account balances above the value of 1 ETH into the Homestead Genesis block."

This was what was said a while back, but that decision has since been reversed and the text here will need to change to reflect that.

See:
https://blog.ethereum.org/2015/07/22/frontier-is-coming-what-to-expect-and-how-to-prepare/
section "Bugs, Issues and Complications"

"Many of the planned Frontier gotchas (which included a chain reset at Homestead, limiting mining rewards to 10%, and centralized checkpointing) were deemed unnecessary."

**Comment by alexvandesande** [comment]
Fixed now on #34
