### ISSUE TITLE
Consistent use of -sed/-zed

### ISSUE THREAD

**Issue by linagee** [ethereum/frontier-release#44]
Please pick a version of decentralized / decentralised and centralized / centralised.
The site right now has both versions.

Being from America, I prefer the -zed, but I guess British English (UK) says -sed.
I think the thing here would to at least be consistent.
I can submit a PR if the choice is made. (Or whoever answers this can probably grep just as easy. :+1: )

**Comment by linagee** [comment]
Also decimal point vs comma in numbers, this appears once: "10 000"

**Comment by linagee** [comment]
Alex said -zed wins!

**Comment by alexvandesande** [comment]
solved

**Comment by alexvandesande** [comment]
"zed's dead babe, zed's dead."
