### ISSUE TITLE
Fix tutorial wording in these three places.

### ISSUE THREAD

**Issue by s-graff** [ethereum/frontier-release#53]
Where it says "If instead the command returns an error, then you need to install it."
Should be more like "If the command does not return ['Solidity'], then you need to install it."

Incorrect phrase:  "Unlike last time we will not be making a call as we wish to change something on the blockchain."
Reason:  Actually, we WILL be making a call.

Incorrect phrase:  "(or at least until the frontier contracts are all wiped)"
Reason:  This is no longer in the plans.

**Comment by linagee** [comment]
#55 addresses the 3rd one

**Comment by linagee** [comment]
#56 addresses the 2nd one

**Comment by linagee** [comment]
#57 addresses the 1st one

**Comment by cubedro** [comment]
Has everything been addressed? Is this issue good to close?
