### ISSUE TITLE
geth "failed to load releases"

### ISSUE THREAD

**Issue by jlopp** [ethereum/frontier-release#928]
I seem to have encountered an edge case that causes the geth download page to fail. This doesn't happen to other folks I've asked, but it happens on every machine on my network - multiple flavors of Linux and Windows and in every browser I've tried. Worth noting that all of the machines are behind a VPN, so that may be breaking some script?
![screenshot from 2018-12-03 15-12-38](https://user-images.githubusercontent.com/288011/49399480-5bb5a080-f70f-11e8-8250-35b2b0266ab3.png)

**Comment by matawinb** [comment]
D

**Comment by FaysalM** [comment]
@jlopp it would probably help if you included the network route? Unless this is no longer an issue? I tried over VPN and works fine.

**Comment by jlopp** [comment]
Seems to be fixed now

**Comment by amakori** [comment]
Very surprising that this bug persists to this day.

**Comment by jlopp** [comment]
Works for me, though I bet you get this error if the call to https://gethstore.blob.core.windows.net/builds?restype=container&comp=list&maxresults=5000&prefix=geth- fails

**Comment by amakori** [comment]
> Works for me, though I bet you get this error if the call to https://gethstore.blob.core.windows.net/builds?restype=container&comp=list&maxresults=5000&prefix=geth- fails

Is there another downloads page?

**Comment by jlopp** [comment]
Other options listed at: https://github.com/ethereum/go-ethereum/releases
