### ISSUE TITLE
Please add reference to new repo

### ISSUE THREAD

**Issue by ethers** [ethereum/frontier-release#948]
The current repo title just says "[ARCHIVED] Ethereum Foundation website from 2016-2019".  A pointer to the new one would be helpful.

**Comment by samajammin** [comment]
@evertonfraga do you have edit access on this repo? I agree it would be helpful to add a link to https://github.com/ethereum/ethereum-org-website/ in this repo's title/description.

**Comment by Souptacular** [comment]
I granted you permissions @samajammin.

**Comment by samajammin** [comment]
Thanks @Souptacular ❤️
