### ISSUE TITLE
Absolutely no peers

### ISSUE THREAD

**Issue by Ulysseus** [ethereum/frontier-release#97]
Running Geth, only got three peers, had MaxPeers set to 25
Punched through modem
  465 nat.go:111] mapped network port udp:30303 -> 30303 (ethereum discovery) using UPNP IGDv1-PPP1
I0730 22:03:58.682524     465 nat.go:111] mapped network port tcp:30303 -> 30303 (ethereum p2p) using UPNP IGDv1-PPP1

Internet running
net on the console shows
{
  listening: true,
  peerCount: 0,
  version: '1',
  addPeer: function (),
  getListening: function (),
  getPeerCount: function (),
  getVersion: function ()
}
I tried deleting blockchain extra and nodes and state directories, rebooting, but same behavior

**Comment by Ulysseus** [comment]
Okay I can get one peer, but really?

**Comment by Ulysseus** [comment]
I am in Southern Africa, pretty sure its because of the latency, at least 200 -400ms

**Comment by cubedro** [comment]
you could try adding the following flag to geth:
```
 --bootnodes "enode://09fbeec0d047e9a37e63f60f8618aa9df0e49271f3fadb2c070dc09e2099b95827b63a8b837c6fd01d0802d457dd83e3bd48bd3e6509f8209ed90dabbc30e3d3@52.16.188.185:30303"
```

**Comment by Ulysseus** [comment]
Thx, changed to a better ISP seemed to resolve the issue.

**Comment by cubedro** [comment]
cool
